from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from .config import CURRENT_CONFIG_VERSION


PARA_DIRECTORIES = (
    "Inbox",
    "Projects",
    "Areas",
    "Resources",
    "Archive",
)
INSTALLATION_VERSION = 2


@dataclass(frozen=True)
class ParaVaultInitialization:
    vault_root: Path
    config_path: Path
    personal_context_path: Path
    setup_state_path: Path
    update_state_path: Path
    created_directories: tuple[Path, ...]


def initialize_para_vault(
    vault_root: Path,
    config_path: Path,
) -> ParaVaultInitialization:
    """Create an empty PARA vault and its local Brainiac installation files.

    This is intentionally not a migration tool. A non-empty directory or an
    existing config requires a separate, explicit migration workflow.
    """
    vault_root = vault_root.expanduser().resolve()
    config_path = config_path.expanduser().resolve()
    workspace_root = config_path.parent.parent
    personal_context_path = workspace_root / "brainiac_me.md"
    setup_state_path = workspace_root / ".state" / "setup.yml"
    update_state_path = workspace_root / ".state" / "update_check.yml"
    _validate_preconditions(
        vault_root,
        config_path,
        personal_context_path,
        setup_state_path,
        update_state_path,
    )

    created_directories = tuple(vault_root / relative_path for relative_path in PARA_DIRECTORIES)
    for directory in created_directories:
        directory.mkdir(parents=True, exist_ok=False)

    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(_brainiac_config_text(vault_root), encoding="utf-8")
    personal_context_path.write_text(_personal_context_text(), encoding="utf-8")
    setup_state_path.parent.mkdir(parents=True, exist_ok=True)
    setup_state_path.write_text(_setup_state_text(), encoding="utf-8")
    update_state_path.write_text(_update_state_text(), encoding="utf-8")

    return ParaVaultInitialization(
        vault_root=vault_root,
        config_path=config_path,
        personal_context_path=personal_context_path,
        setup_state_path=setup_state_path,
        update_state_path=update_state_path,
        created_directories=created_directories,
    )


def _validate_preconditions(vault_root: Path, config_path: Path, *installation_paths: Path) -> None:
    try:
        config_path.relative_to(vault_root)
    except ValueError:
        pass
    else:
        raise ValueError(
            f"Brainiac config must stay outside the vault root: {config_path}. "
            "Choose a local Brainiac workspace outside the vault."
        )
    for path in (config_path, *installation_paths):
        if path.exists():
            raise ValueError(f"Brainiac installation file already exists: {path}. Refusing to overwrite it.")
    if vault_root.exists() and not vault_root.is_dir():
        raise ValueError(f"Vault root is not a directory: {vault_root}")
    if vault_root.exists() and any(vault_root.iterdir()):
        raise ValueError(
            f"Vault root is not empty: {vault_root}. "
            "`brainiac init` creates new vaults only."
        )


def _brainiac_config_text(vault_root: Path) -> str:
    return f'''# Local Brainiac CLI configuration generated by `brainiac init`.

brainiac:
  config_version: {CURRENT_CONFIG_VERSION}

vault:
  name: "{_yaml_quote(vault_root.name)}"
  root: "{_yaml_quote(vault_root.as_posix())}"
  layout: para

exclude:
  - ".obsidian/"
  - ".trash/"

source_formats:
  markdown:
    - "*.md"
  canvas:
    - "*.canvas"
  structured:
    - "*.json"
    - "*.yml"
    - "*.yaml"
    - "*.csv"

index:
  path: "memory/index/brainiac.sqlite"
  disposable: true
'''


def _personal_context_text() -> str:
    return f'''# Brainiac Personal Context

> This local file is yours. It overrides `brainiac.md` when they conflict.
> Keep secrets outside this file.

## Profile

```yaml
installed_version: {INSTALLATION_VERSION}
language: ""
```

## Vault Context

- Add vocabulary, aliases, and domain-specific retrieval hints here.

## Local Projects

<!--
### Project Name

Local path: `/path/to/project`

| File | When to load |
|------|--------------|
| `README.md` | Product and architecture questions |
-->

## Personal Patterns

- Add preferences and custom working instructions here.
'''


def _setup_state_text() -> str:
    return '''status: in_progress
current_step: personal_context
last_note: "Brainiac installation created. Collect personal context."
'''


def _update_state_text() -> str:
    return f'''last_checked_at: ""
last_result: not_checked
last_local_version: {INSTALLATION_VERSION}
'''


def _yaml_quote(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
