from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path


PARA_DIRECTORIES = (
    "Inbox",
    "Projects",
    "Areas",
    "Resources",
    "Archive",
)


@dataclass(frozen=True)
class ParaVaultInitialization:
    vault_root: Path
    vault_config_path: Path
    created_directories: tuple[Path, ...]


def initialize_para_vault(
    vault_root: Path,
    vault_config_path: Path,
) -> ParaVaultInitialization:
    """Create an empty, new PARA vault and its local vault configuration.

    This is intentionally not a migration tool. A non-empty directory or an
    existing config requires a separate, explicit migration workflow.
    """
    vault_root = vault_root.expanduser().resolve()
    vault_config_path = vault_config_path.expanduser().resolve()
    _validate_preconditions(vault_root, vault_config_path)

    created_directories = tuple(vault_root / relative_path for relative_path in PARA_DIRECTORIES)
    for directory in created_directories:
        directory.mkdir(parents=True, exist_ok=False)

    vault_config_path.parent.mkdir(parents=True, exist_ok=True)
    vault_config_path.write_text(_vault_config_text(vault_root), encoding="utf-8")

    return ParaVaultInitialization(
        vault_root=vault_root,
        vault_config_path=vault_config_path,
        created_directories=created_directories,
    )


def _validate_preconditions(vault_root: Path, vault_config_path: Path) -> None:
    try:
        vault_config_path.relative_to(vault_root)
    except ValueError:
        pass
    else:
        raise ValueError(
            f"Vault config must stay outside the vault root: {vault_config_path}. "
            "Choose a local Brainiac workspace outside the vault."
        )
    if vault_config_path.exists():
        raise ValueError(f"Vault config already exists: {vault_config_path}. Refusing to overwrite it.")
    if vault_root.exists() and not vault_root.is_dir():
        raise ValueError(f"Vault root is not a directory: {vault_root}")
    if vault_root.exists() and any(vault_root.iterdir()):
        raise ValueError(
            f"Vault root is not empty: {vault_root}. "
            "`brainiac init` creates new vaults only; use the future migration workflow for an existing vault."
        )


def _vault_config_text(vault_root: Path) -> str:
    return f'''# Local Brainiac vault configuration generated by `brainiac init`.

vault:
  version: 1
  name: "{_yaml_quote(vault_root.name)}"
  root: "{_yaml_quote(vault_root.as_posix())}"
  layout: para

exclude:
  - ".obsidian/"
  - ".trash/"

source_formats:
  markdown:
    - "*.md"
  canvas:
    - "*.canvas"
  structured:
    - "*.json"
    - "*.yml"
    - "*.yaml"
    - "*.csv"

index:
  path: "memory/index/brainiac.sqlite"
  disposable: true
'''
def _yaml_quote(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')
